// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Your Name",
            "email": "your-email@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notifications/{providerId}": {
            "get": {
                "tags": ["notifications"],
                "summary": "Get notifications by provider",
                "description": "Retrieves new notifications for the specified provider and then clears them.",
                "operationId": "getNotificationsByProvider",
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "providerId",
                        "in": "path",
                        "description": "ID of the provider",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Notification"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid providerId"
                    }
                }
            }
        }
    },
    "definitions": {
        "Notification": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "description": "Internal identifier"
                },
                "providerId": {
                    "type": "integer",
                    "description": "Provider ID"
                },
                "score": {
                    "type": "integer",
                    "description": "Rating score"
                },
                "comment": {
                    "type": "string",
                    "description": "Optional comment"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Timestamp of rating creation"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Notification Service API",
	Description:      "This service consumes rating-created events from Kafka and provides notifications for providers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
